db:
  image: mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: gallery
    MYSQL_PASSWORD: gallery
    MYSQL_DATABASE: gallery

phpfpm:
  build: ./docker/phpfpm
  volumes:
     - "./source:/var/www/html"
  links:
     - db

nginx:
  image: nginx
  ports:
    - "8080:80"
  volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
  volumes_from:
    - phpfpm
  links:
    - phpfpm

phpcli:
  build: ./docker/phpcli
  stdin_open: true
  volumes_from:
    - phpfpm