<?php

namespace Gallery\Bundles\ApiBundle\Repository;

use Doctrine\ORM\Query\Expr;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends \Doctrine\ORM\EntityRepository
{
    const IMAGES_IN_ALBUM_PREVIEW = 10;
    
    public function findAlbumWithPreviews()
    {
        $query = $this->createQueryBuilder('a')
            ->select('a','i')
            ->leftJoin('a.albumImages', 'i')
            ->where('(
                SELECT COUNT(i1.id) 
                FROM ApiBundle:Image i1
                WHERE i1.album = i.album AND i1.id < i.id 
            ) < :image_number')
            ->setParameter(':image_number', self::IMAGES_IN_ALBUM_PREVIEW)
            ->getQuery()
          ;
        return $query->getResult();
    }
}
